// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTQNW34Ls3q-h4TRmJ_QBmbmPsFQrW2MY',
    appId: '1:933192097589:web:5af4fcb322b26e2c0bf67c',
    messagingSenderId: '933192097589',
    projectId: 'appfaceit-5d80c',
    authDomain: 'appfaceit-5d80c.firebaseapp.com',
    storageBucket: 'appfaceit-5d80c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDGU-PK5TSGRpGgQgvgrhFhabM_7Aj_2E',
    appId: '1:933192097589:android:1ea63051b88e96d90bf67c',
    messagingSenderId: '933192097589',
    projectId: 'appfaceit-5d80c',
    storageBucket: 'appfaceit-5d80c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXUoSy9V6yca8jiSIIZMDlCc9e3C8jGhE',
    appId: '1:933192097589:ios:f77356d265fd93470bf67c',
    messagingSenderId: '933192097589',
    projectId: 'appfaceit-5d80c',
    storageBucket: 'appfaceit-5d80c.firebasestorage.app',
    iosBundleId: 'vei.faceItApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXUoSy9V6yca8jiSIIZMDlCc9e3C8jGhE',
    appId: '1:933192097589:ios:f77356d265fd93470bf67c',
    messagingSenderId: '933192097589',
    projectId: 'appfaceit-5d80c',
    storageBucket: 'appfaceit-5d80c.firebasestorage.app',
    iosBundleId: 'vei.faceItApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTQNW34Ls3q-h4TRmJ_QBmbmPsFQrW2MY',
    appId: '1:933192097589:web:fecb23c2a23ed0470bf67c',
    messagingSenderId: '933192097589',
    projectId: 'appfaceit-5d80c',
    authDomain: 'appfaceit-5d80c.firebaseapp.com',
    storageBucket: 'appfaceit-5d80c.firebasestorage.app',
  );

}